Vagrant.configure("2") do |config|
  config.vm.box = "talos-linux"
  config.vm.boot_timeout = 0
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  workers = [
    { name: "worker1", mac: "52:54:00:4e:0b:04" },
    { name: "worker2", mac: "52:54:00:07:41:56" },
    { name: "worker3", mac: "52:54:00:a1:b2:c3" },
  ]

  workers.each do |w|
    config.vm.define w[:name] do |vm|
      vm.vm.network "public_network",
        dev: "br0",
        mode: "bridge",
        type: "bridge",
        mac: w[:mac]

      vm.vm.provider :libvirt do |v|
        v.uri = "qemu:///system"
        v.storage_pool_name = "home-pool"
        v.machine_virtual_size = 40
        v.memory = 4096
        v.cpus   = 4
        v.cpu_mode = "host-passthrough"
        v.mgmt_attach = false
        v.storage :file, size: '160G', pool: 'home-pool'
      end
    end
  end
end
